# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_message', models.CharField(max_length=250, null=True)),
                ('system_user_message', models.CharField(blank=True, max_length=250, null=True)),
                ('support_date', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(null=True)),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_support.Support')),
            ],
        ),
    ]
