# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('online_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='system_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.SystemUser'),
        ),
    ]
