<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns0="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MX_ManagerGetIdLastLoginCredentialsWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL">
	<types>
		<xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL">
			<xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="STATIC_URLsoap/manager/get/soap.xsd"/>
		</xsd:schema>
	</types>
	<message name="MX_ManagerGetIdLastLoginCredentialsWSDLOperationRequest">
		<part name="id" type="xsd:string"></part>
	</message>
	<message name="MX_ManagerGetIdLastLoginCredentialsWSDLOperationResponse">
		<part type="ns0:MXManagerSelectCredentials_ResponseR" name="Credentials"></part>
		<part name="isSuccess" type="xsd:string"></part>
	</message>
	<portType name="MX_ManagerGetIdLastLoginCredentialsWSDLPortType">
		<operation name="MX_ManagerGetIdLastLoginCredentialsWSDLOperation">
			<input message="tns:MX_ManagerGetIdLastLoginCredentialsWSDLOperationRequest" name="input1"></input>
			<output message="tns:MX_ManagerGetIdLastLoginCredentialsWSDLOperationResponse" name="output1"></output>
		</operation>
	</portType>
	<binding name="MX_ManagerGetIdLastLoginCredentialsWSDLBinding" type="tns:MX_ManagerGetIdLastLoginCredentialsWSDLPortType">
		<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="MX_ManagerGetIdLastLoginCredentialsWSDLOperation">
			<soap:operation/>
			<input name="input1">
				<soap:body namespace="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL" use="literal"/>
			</input>
			<output name="output1">
				<soap:body namespace="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL" use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="MX_ManagerGetIdLastLoginCredentialsWSDLService">
		<port binding="tns:MX_ManagerGetIdLastLoginCredentialsWSDLBinding" name="MX_ManagerGetIdLastLoginCredentialsWSDLPort">
			<soap:address location="http://a-PC:9080/MX_ManagerGetIdLastLoginCredentialsWSDLService/MX_ManagerGetIdLastLoginCredentialsWSDLPort"/>
		</port>
	</service>
	<plnk:partnerLinkType name="MX_ManagerGetIdLastLoginCredentialsWSDL">
<!--
 A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.
-->
<plnk:role name="MX_ManagerGetIdLastLoginCredentialsWSDLPortTypeRole" portType="tns:MX_ManagerGetIdLastLoginCredentialsWSDLPortType"/>
</plnk:partnerLinkType>
</definitions>