<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL" xmlns:ns0="http://j2ee.netbeans.org/xsd/tableSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" name="MX_ManagerGetIdLastLoginCredentialsWSDL" targetNamespace="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL">
  <types>
    <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL">
      <xsd:import namespace="http://j2ee.netbeans.org/xsd/tableSchema" schemaLocation="STATIC_URLsoap/manager/get/soap.xsd"/>
    </xsd:schema>
  </types>
  <message name="MX_ManagerGetIdLastLoginCredentialsWSDLOperationResponse">
    <part name="Credentials" type="ns0:MXManagerSelectCredentials_ResponseR"></part>
    <part name="isSuccess" type="xsd:string"></part>
  </message>
  <message name="MX_ManagerGetIdLastLoginCredentialsWSDLOperationRequest">
    <part name="idOrEmail" type="xsd:string"></part>
    <part name="isId" type="xsd:boolean"></part>
  </message>
  <portType name="MX_ManagerGetIdLastLoginCredentialsWSDLPortType">
    <operation name="MX_ManagerGetIdLastLoginCredentialsWSDLOperation">
      <input name="input1" message="tns:MX_ManagerGetIdLastLoginCredentialsWSDLOperationRequest"></input>
      <output name="output1" message="tns:MX_ManagerGetIdLastLoginCredentialsWSDLOperationResponse"></output>
    </operation>
  </portType>
  <binding name="MX_ManagerGetIdLastLoginCredentialsWSDLBinding" type="tns:MX_ManagerGetIdLastLoginCredentialsWSDLPortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="MX_ManagerGetIdLastLoginCredentialsWSDLOperation">
      <soap:operation/>
      <input name="input1">
        <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL"/>
      </input>
      <output name="output1">
        <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/MX_ManagerGetIdLastLoginCredentials/src/MX_ManagerGetIdLastLoginCredentialsWSDL"/>
      </output>
    </operation>
  </binding>
  <service name="MX_ManagerGetIdLastLoginCredentialsWSDLService">
    <port name="MX_ManagerGetIdLastLoginCredentialsWSDLPort" binding="tns:MX_ManagerGetIdLastLoginCredentialsWSDLBinding">
      <soap:address location="http://a-PC:9080/MX_ManagerGetIdLastLoginCredentialsWSDLService/MX_ManagerGetIdLastLoginCredentialsWSDLPort"/>
    </port>
  </service>
  <plnk:partnerLinkType name="MX_ManagerGetIdLastLoginCredentialsWSDL">
    <!--
     A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
    In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
    A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.
    -->
    <plnk:role name="MX_ManagerGetIdLastLoginCredentialsWSDLPortTypeRole" portType="tns:MX_ManagerGetIdLastLoginCredentialsWSDLPortType"/>
  </plnk:partnerLinkType>
</definitions>